name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: |
          docker build -t ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}app:$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 300

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}app:$(echo $GITHUB_SHA | head -c7)
